# Copyright (c) 2014 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Pathname.new(__FILE__).ascend do |p|
  if (p + '.ruby-version').exist?
    ROOT = p.freeze
    break
  end
end

VM_MEMORY = ENV.fetch('VM_MEMORY', 4 * 1024).to_i.freeze
VM_CORES  = ENV.fetch('VM_CORES', `sysctl -n hw.ncpu`).to_i.freeze

Vagrant.configure('2') do |config|

  config.vm.define 'centos6' do |c|
    c.vm.box = 'centos664'
    c.vm.provision 'shell', path: 'centos6.sh'
    c.vm.provision 'shell', path: 'rbenv.sh', :privileged => false
    c.vm.synced_folder ROOT, '/java-buildpack-dependency-builder'

    c.vm.provider('virtualbox') do |vb, override|
      vb.cpus   = VM_CORES
      vb.memory = VM_MEMORY

      override.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/centos664-virtualbox.box'
    end

    c.vm.provider('vmware_fusion') do |vmw, override|
      vmw.vmx['memsize']  = VM_MEMORY
      vmw.vmx['numvcpus'] = VM_CORES

      override.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/centos664-vmware_desktop.box'
    end
  end

  config.vm.define 'lucid' do |l|
    l.vm.box = 'lucid64'
    l.vm.provision 'shell', path: 'lucid.sh'
    l.vm.provision 'shell', path: 'rbenv.sh', :privileged => false
    l.vm.synced_folder ROOT, '/java-buildpack-dependency-builder'

    l.vm.provider('virtualbox') do |vb, override|
      vb.cpus   = VM_CORES
      vb.memory = VM_MEMORY

      override.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/lucid64-virtualbox.box'
    end

    l.vm.provider('vmware_fusion') do |vmw, override|
      vmw.vmx['memsize']  = VM_MEMORY
      vmw.vmx['numvcpus'] = VM_CORES

      override.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/lucid64-vmware_desktop.box'
    end
  end

  config.vm.define 'mountainlion' do |m|
    m.vm.box = 'mountainlion64'
    m.vm.provision 'shell', path: 'xquartz.sh'
    m.vm.provision 'shell', path: 'mountainlion.sh', :privileged => false
    m.vm.provision 'shell', path: 'rbenv.sh', :privileged => false
    m.vm.synced_folder ROOT, '/java-buildpack-dependency-builder', type: 'rsync'

    m.vm.provider('virtualbox') do |vb, override|
      vb.cpus   = VM_CORES
      vb.memory = VM_MEMORY

      override.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/mountainlion64-virtualbox.box'
    end

    m.vm.provider('vmware_fusion') do |vmw, override|
      vmw.vmx['memsize']  = VM_MEMORY
      vmw.vmx['numvcpus'] = VM_CORES

      override.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/mountainlion64-vmware_desktop.box'
    end

  end

  config.vm.define 'precise' do |p|
    p.vm.box = 'precise64'
    p.vm.provision 'shell', path: 'precise.sh'
    p.vm.provision 'shell', path: 'rbenv.sh', :privileged => false
    p.vm.synced_folder ROOT, '/java-buildpack-dependency-builder'

    p.vm.provider('virtualbox') do |vb, override|
      vb.cpus   = VM_CORES
      vb.memory = VM_MEMORY

      override.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/precise64-virtualbox.box'
    end

    p.vm.provider('vmware_fusion') do |vmw, override|
      vmw.vmx['memsize']  = VM_MEMORY
      vmw.vmx['numvcpus'] = VM_CORES

      override.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/precise64-vmware_desktop.box'
    end
  end

  config.vm.define 'trusty' do |t|
    t.vm.box = 'trusty64'
    t.vm.provision 'shell', path: 'trusty.sh'
    t.vm.provision 'shell', path: 'rbenv.sh', :privileged => false
    t.vm.synced_folder ROOT, '/java-buildpack-dependency-builder'

    t.vm.provider('virtualbox') do |vb, override|
      vb.cpus   = VM_CORES
      vb.memory = VM_MEMORY

      override.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/trusty64-virtualbox.box'
    end

    t.vm.provider('vmware_fusion') do |vmw, override|
      vmw.vmx['memsize']  = VM_MEMORY
      vmw.vmx['numvcpus'] = VM_CORES

      override.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/trusty64-vmware_desktop.box'
    end
  end

end
