# Copyright (c) 2013 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Vagrant.configure('2') do |config|

  config.vm.synced_folder '../../../', '/java-buildpack-dependency-builder'

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', '2048', '--cpus', `sysctl -n hw.ncpu`.strip]
  end

  config.vm.define :centos6 do |centos6|
    centos6.vm.box = 'centos664'
    centos6.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/centos664.box'
    centos6.vm.provision :shell, :path => 'centos6.sh'
  end

  config.vm.define :lucid do |lucid|
    lucid.vm.box = 'lucid64'
    lucid.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/lucid64.box'
    lucid.vm.provision :shell, :path => 'lucid_and_precise.sh'
  end

  config.vm.define :precise do |precise|
    precise.vm.box = 'precise64'
    precise.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/precise64.box'
    precise.vm.provision :shell, :path => 'lucid_and_precise.sh'
  end

  config.vm.define :trusty do |trusty|
    trusty.vm.box = 'trusty64'
    trusty.vm.box_url = 'http://boxes.gopivotal.com.s3.amazonaws.com/trusty64.box'
    trusty.vm.provision :shell, :path => 'trusty.sh'
  end

end
