---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest
    username: ((docker-username))
    password: ((docker-password))

inputs:
- name: java-buildpack-dependency-builder

outputs:
- name: appdynamics-builder
- name: adoptopenjdk-builder
- name: artifactory-builder
- name: corretto-builder
- name: gcs-repository-builder
- name: gradle-builder
- name: http-builder
- name: jprofiler-builder
- name: maven-builder
- name: npm-builder
- name: repository-builder
- name: sky-walking-builder
- name: tomcat-builder
- name: wildfly-builder
- name: your-kit-builder
- name: zulu-builder

caches:
- path: go-module-cache

run:
  path: java-buildpack-dependency-builder/resources/ci/build.sh
